name: github-token-validator
description: Validate that the value looks like a modern GitHub authentication token.
# https://github.blog/2021-04-05-behind-githubs-new-authentication-token-formats/
author: RIMdev <RIMdev@RitterIM.com>
branding:
  icon: 'check-square'  
  color: 'blue'

inputs:

  token:
    required: true

  required:
    required: false
    default: true

  error_if_not_valid:
    required: false
    default: true

runs:
  using: "composite"

  steps:

    - name: Validate token
      uses: ritterim/public-github-actions/actions/regex-validator@v1.5.0
      with:
        value: ${{ inputs.token }}
        regex_pattern: '^(gh[pousr]_[A-Za-z0-9_]{36,251}|github_pat_[a-zA-Z0-9]{22}_[a-zA-Z0-9]{59}|v[0-9]\.[0-9a-f]{40})$'
        required: ${{ inputs.required }}
        error_if_not_valid: ${{ inputs.error_if_not_valid }}
