name: npm-package-scope-validator
description: Validate that the NPM package scope value matches a regex pattern.  The regex pattern for this validator is stricter than what NPM allows.
author: RIMdev <RIMdev@RitterIM.com>
branding:
  icon: 'check-square'  
  color: 'blue'

inputs:

  npm_scope:
    required: true

  required:
    required: false
    default: true

  error_if_not_valid:
    required: false
    default: true

runs:
  using: "composite"

  steps:

    - name: Validate
      uses: ritterim/public-github-actions/actions/regex-validator@v1.15.0
      with:
        value: ${{ inputs.npm_scope }}
        regex_pattern: '^[a-z0-9\-]{5,25}$'
        required: ${{ inputs.required }}
        error_if_not_valid: ${{ inputs.error_if_not_valid }}
