name: version-number-validator
description: Validate that the version number looks like a version number.
author: RIMdev <RIMdev@RitterIM.com>
branding:
  icon: 'check-square'  
  color: 'blue'

inputs:

  version:
    required: true

  allow_v_prefix:
    description: Whether 'v' is allowed at the start of the version value.  Note that you must pass in "true" as 'true' (a lowercase string) for this to work.
    required: false
    default: false

  required:
    required: false
    default: true

  error_if_not_valid:
    required: false
    default: true

runs:
  using: "composite"

  steps:

    - name: Validate with 'v' prefix
      uses: ritterim/public-github-actions/actions/regex-validator@v1.9.0
      if: inputs.allow_v_prefix == 'true'
      with:
        value: ${{ inputs.version }}
        regex_pattern: '^v(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)(-(0|[1-9A-Za-z-][0-9A-Za-z-]*)(\.[0-9A-Za-z-]+)*)?(\+[0-9A-Za-z-]+(\.[0-9A-Za-z-]+)*)?$'
        required: ${{ inputs.required }}
        error_if_not_valid: ${{ inputs.error_if_not_valid }}

    - name: Validate without 'v' prefix
      uses: ritterim/public-github-actions/actions/regex-validator@v1.9.0
      if: inputs.allow_v_prefix != 'true'
      with:
        value: ${{ inputs.version }}
        regex_pattern: '^(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)(-(0|[1-9A-Za-z-][0-9A-Za-z-]*)(\.[0-9A-Za-z-]+)*)?(\+[0-9A-Za-z-]+(\.[0-9A-Za-z-]+)*)?$'
        required: ${{ inputs.required }}
        error_if_not_valid: ${{ inputs.error_if_not_valid }}
