name: npm-config-github-packages-repository
description: Configure the '.npmrc' file correctly to authenticate to GitHub Packages.
author: ritterim
branding:
  icon: 'download-cloud'  
  color: 'gray-dark'

# https://dev.to/github/the-githubtoken-in-github-actions-how-it-works-change-permissions-customizations-3cgp

inputs:

  github_token:
    description: A GitHub Token that can be used to access the GitHub Packages repository.
    required: true

  npm_scope:
    description: The NPM 'scope' value to use.  Default is 'ritterim' as it needs to match the GitHub organization value.
    required: false
    default: ritterim

runs:
  using: "composite"

  steps:

    - name: Validate inputs.npm_scope
      uses: ritterim/public-github-actions/actions/npm-package-scope-validator@v1.17
      with:
        npm_scope: ${{ inputs.npm_scope }}

    - name: Debug inputs.github_token
      shell: bash
      if: runner.debug == '1'
      env:
        GHTOKEN: ${{ inputs.github_token }}
      run: |
        if [ "${#GHTOKEN}" -gt 5 ]; then
          echo "Token length check: pass"
        else
          echo "Token length check: fail"
        fi

    - name: Validate inputs.github_token
      uses: ritterim/public-github-actions/actions/github-token-validator@v1.17
      with:
        token: ${{ inputs.github_token }}

    - name: Verify current NPM config
      shell: bash
      run: npm config list

    - name: Configure .npmrc GitHub Packages registry
      shell: bash
      env:
        GHTOKEN: ${{ inputs.github_token }}
        NPMSCOPE: ${{ inputs.npm_scope }}
      run: |
        npm config set "@${NPMSCOPE}:registry=https://npm.pkg.github.com"
        npm config set "//npm.pkg.github.com/:_authToken=${GHTOKEN}"
