name: npm-check-package-lock-publish-dates
description: Scan the package-lock.json and lookup last publish dates for all resolved versions.
author: RIMdev <RIMdev@RitterIM.com>
branding:
  icon: 'check-square'  
  color: 'green'

inputs:

  npm_project_directory:
    description: Location of the package.json file for the NPM package.
    required: false
    default: ./

  cache_directory:
    description: Location of the cache directory for NPM lookups.
    required: false
    default: "~/.cache/npm-publish-dates"

  minimum_publish_age_days:
    description: Error out if any packages were published within the past N days.
    required: false
    default: "7"

runs:
  using: "composite"

  steps:
    - name: Check package lock publish dates.
      shell: pwsh
      env:
        ProjectDirectory: ${{ inputs.npm_project_directory }}
        CacheDirectory: ${{ inputs.cache_directory }}
        MinimumPublishAgeDays: ${{ inputs.minimum_publish_age_days }}
      run: |
        ./npm-check-package-lock-publish-dates.ps1 -ProjectDirectory $env:ProjectDirectory -MinimumPublishAgeDays $env:MinimumPublishAgeDays -CacheDirectory $env:CacheDirectory
        