name: Azure Zip Deploy

permissions:
  contents: read
  id-token: write

on:
  workflow_call:
    inputs:
      artifact_name:
        required: true
        type: string
      artifact_filename:
        required: true
        type: string
      azure_web_app_slot_name:
        required: false
        type: string
        default: 'production'
      azure_web_app_deploy_subscription_id:
        required: true
        type: string
      azure_web_app_name:
        required: true
        type: string
      environment_name:
        required: false
        type: string
        default: ''

jobs:

  azure-webapps-zip-deploy:
    name: Azure Zip Deploy
    runs-on: ubuntu-latest
    timeout-minutes: 30
    environment:
      name: ${{ inputs.environment_name }}

    concurrency:
      group: deploy-${{ inputs.azure_web_app_name }}-${{ inputs.azure_web_app_slot_name }}
      cancel-in-progress: false

    env:
      AZUREDEPLOYSUBSCRIPTIONID: ${{ inputs.azure_web_app_deploy_subscription_id }}

    steps:

      - name: Validate inputs.azure_web_app_deploy_subscription_id
        uses: ritterim/public-github-actions/actions/guid-validator@v1.17
        with:
          guid: ${{ env.AZUREDEPLOYSUBSCRIPTIONID }}

      - name: Download artifact from build job
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: ${{ inputs.artifact_name }}

      - run: ls -la
        if: runner.debug == '1'

      - uses: azure/login@7ddb5af1ef8758cf1353cf3b42f940aee27ba21c # v3.0.2
        with:
          client-id: ${{ vars.ARTIFACT_DEPLOYER_AZURE_CLIENT_ID }}
          tenant-id: ${{ vars.ARTIFACT_DEPLOYER_AZURE_TENANT_ID }}
          subscription-id: ${{ vars.ARTIFACT_DEPLOYER_AZURE_SUBSCRIPTION_ID }}

      # The azure/webapps-deploy action doesn't seem to provide a way to specify the subscription ID.
      # Unless we change the default subscription, it will fail to find the app-name.
      - run: az account set --subscription "${AZUREDEPLOYSUBSCRIPTIONID}"

      - name: Zip Deploy to Azure
        uses: azure/webapps-deploy@02a81bead70021f5284939794bcec79c271ab383 # v3.0.8
        with:
          app-name: ${{ inputs.azure_web_app_name }}
          slot-name: ${{ inputs.azure_web_app_slot_name }}
          package: ${{ inputs.artifact_filename }}
